base_url = "https://www.accuweather.com/"
search_box_CSS = "input.search-input"
istanbul_search_box_XPATH = "/html/body/div[@class='template-root']//div[@class='results-container']/div[@class='search-bar-result search-result source-accuweather']"
current_location_XPATH = "/html/body/div[@class='template-root']/div[1]//div[@class='search-results']/div[1]"
search_icon_CSS = ".search-icon"
result_Message_XPATH = "/html/body/div[@class='template-root']//div[@class='no-results-text']"
result_Message2_XPATH = "/html/body/div[@class='template-root']//div[@class='no-results-helper']"
today_XPATH = "/html//div[@class='template-root']//div[@class='subnav-items']/a[@href='/tr/tr/istanbul/318251/weather-forecast/318251']/h2[.='Bugün']"
day_real_feel_shade_XPATH ="/html/body/div[@class='template-root']/div[7]//a[@href='/tr/tr/istanbul/318251/current-weather/318251']//div[@class='cur-con-weather-card__panel details-container']/div[1]/span[@class='label']"
day_wind_XPATH ="/html/body/div[@class='template-root']/div[7]//a[@href='/tr/tr/istanbul/318251/current-weather/318251']//div[@class='cur-con-weather-card__panel details-container']/div[2]/span[@class='label']"
day_strong_wind_XPATH ="/html/body/div[@class='template-root']/div[7]//a[@href='/tr/tr/istanbul/318251/current-weather/318251']//div[@class='cur-con-weather-card__panel details-container']/div[3]/span[@class='label']"
day_air_quality_XPATH = "/html/body/div[@class='template-root']/div[7]//a[@href='/tr/tr/istanbul/318251/current-weather/318251']//div[@class='cur-con-weather-card__panel details-container']/div[4]/span[@class='label']"
hourly_XPATH = "/html//div[@class='template-root']//div[@class='subnav-items']/a[@href='/tr/tr/istanbul/318251/hourly-weather-forecast/318251']/span[.='Saat başı']"
daily_XPATH = "/html//div[@class='template-root']//div[@class='subnav-items']/a[@href='/tr/tr/istanbul/318251/daily-weather-forecast/318251']/span[.='Günlük']"
hourly_radar_XPATH = "/html//div[@class='template-root']//div[@class='subnav-items']/a[@href='/tr/tr/istanbul/318251/weather-radar/318251']/span[.='Radar']"
minutecast_XPATH = "/html//div[@class='template-root']//div[@class='subnav-items']/a[@href='/tr/tr/istanbul/318251/minute-weather-forecast/318251']/span[.='MinuteCast']"
day_night_forecast_XPATH = "/html//div[@class='template-root']//div[@class='subnav-items']/a[@href='/tr/tr/istanbul/318251/july-weather/318251']/span[.='Aylık']"
weather_news_CSS = ".video-wall-icon svg"
air_quality_XPATH = "/html//div[@class='template-root']//div[@class='subnav-items']/a[@href='/tr/tr/istanbul/318251/air-quality-index/318251']/span[.='Hava Kalitesi']"
health_and_activities_XPATH = "/html//div[@class='template-root']/div[@class='page-subnav']/div//a[@href='/tr/tr/istanbul/318251/health-activities/318251']"
